<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>CustomIngots.API</AssemblyName>
    <RootNamespace>CustomIngots.API</RootNamespace>
    <Version>1.2.2</Version>
    <AssemblyVersion>1.2.2.0</AssemblyVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GamePath>/game</GamePath>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <OutputPath>bin/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GamePath)/A Township Tale_Data/Managed/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="IngotDefinition.cs" />
    <Compile Include="IngotCatalog.cs" />
  </ItemGroup>
</Project>
